
export default {
    data: {
        salesType: 'all',
        currentTabKey: '',
        rankingListData: [],
        "visitData": [{
            "x": "2019-01-05",
            "y": 7
        }, {
            "x": "2019-01-06",
            "y": 5
        }, {
            "x": "2019-01-07",
            "y": 4
        }, {
            "x": "2019-01-08",
            "y": 2
        }, {
            "x": "2019-01-09",
            "y": 4
        }, {
            "x": "2019-01-10",
            "y": 7
        }, {
            "x": "2019-01-11",
            "y": 5
        }, {
            "x": "2019-01-12",
            "y": 6
        }, {
            "x": "2019-01-13",
            "y": 5
        }, {
            "x": "2019-01-14",
            "y": 9
        }, {
            "x": "2019-01-15",
            "y": 6
        }, {
            "x": "2019-01-16",
            "y": 3
        }, {
            "x": "2019-01-17",
            "y": 1
        }, {
            "x": "2019-01-18",
            "y": 5
        }, {
            "x": "2019-01-19",
            "y": 3
        }, {
            "x": "2019-01-20",
            "y": 6
        }, {
            "x": "2019-01-21",
            "y": 5
        }],
        "visitData2": [{
            "x": "2019-01-05",
            "y": 1
        }, {
            "x": "2019-01-06",
            "y": 6
        }, {
            "x": "2019-01-07",
            "y": 4
        }, {
            "x": "2019-01-08",
            "y": 8
        }, {
            "x": "2019-01-09",
            "y": 3
        }, {
            "x": "2019-01-10",
            "y": 7
        }, {
            "x": "2019-01-11",
            "y": 2
        }],
        "salesData": [{
            "x": "1月",
            "y": 1175
        }, {
            "x": "2月",
            "y": 341
        }, {
            "x": "3月",
            "y": 1185
        }, {
            "x": "4月",
            "y": 1059
        }, {
            "x": "5月",
            "y": 348
        }, {
            "x": "6月",
            "y": 799
        }, {
            "x": "7月",
            "y": 444
        }, {
            "x": "8月",
            "y": 229
        }, {
            "x": "9月",
            "y": 266
        }, {
            "x": "10月",
            "y": 409
        }, {
            "x": "11月",
            "y": 819
        }, {
            "x": "12月",
            "y": 488
        }],
        "searchData": [{
            "index": 1,
            "keyword": "搜索关键词-0",
            "count": 690,
            "range": 82,
            "status": 0
        }, {
            "index": 2,
            "keyword": "搜索关键词-1",
            "count": 666,
            "range": 84,
            "status": 0
        }, {
            "index": 3,
            "keyword": "搜索关键词-2",
            "count": 2,
            "range": 71,
            "status": 1
        }, {
            "index": 4,
            "keyword": "搜索关键词-3",
            "count": 369,
            "range": 41,
            "status": 0
        }, {
            "index": 5,
            "keyword": "搜索关键词-4",
            "count": 35,
            "range": 48,
            "status": 1
        }, {
            "index": 6,
            "keyword": "搜索关键词-5",
            "count": 871,
            "range": 68,
            "status": 1
        }, {
            "index": 7,
            "keyword": "搜索关键词-6",
            "count": 558,
            "range": 16,
            "status": 0
        }, {
            "index": 8,
            "keyword": "搜索关键词-7",
            "count": 271,
            "range": 46,
            "status": 0
        }, {
            "index": 9,
            "keyword": "搜索关键词-8",
            "count": 943,
            "range": 84,
            "status": 1
        }, {
            "index": 10,
            "keyword": "搜索关键词-9",
            "count": 98,
            "range": 46,
            "status": 0
        }, {
            "index": 11,
            "keyword": "搜索关键词-10",
            "count": 713,
            "range": 49,
            "status": 0
        }, {
            "index": 12,
            "keyword": "搜索关键词-11",
            "count": 237,
            "range": 28,
            "status": 1
        }, {
            "index": 13,
            "keyword": "搜索关键词-12",
            "count": 826,
            "range": 69,
            "status": 0
        }, {
            "index": 14,
            "keyword": "搜索关键词-13",
            "count": 479,
            "range": 76,
            "status": 0
        }, {
            "index": 15,
            "keyword": "搜索关键词-14",
            "count": 563,
            "range": 37,
            "status": 0
        }, {
            "index": 16,
            "keyword": "搜索关键词-15",
            "count": 705,
            "range": 7,
            "status": 0
        }, {
            "index": 17,
            "keyword": "搜索关键词-16",
            "count": 356,
            "range": 89,
            "status": 1
        }, {
            "index": 18,
            "keyword": "搜索关键词-17",
            "count": 920,
            "range": 21,
            "status": 1
        }, {
            "index": 19,
            "keyword": "搜索关键词-18",
            "count": 723,
            "range": 89,
            "status": 1
        }, {
            "index": 20,
            "keyword": "搜索关键词-19",
            "count": 513,
            "range": 82,
            "status": 0
        }, {
            "index": 21,
            "keyword": "搜索关键词-20",
            "count": 502,
            "range": 55,
            "status": 0
        }, {
            "index": 22,
            "keyword": "搜索关键词-21",
            "count": 204,
            "range": 45,
            "status": 1
        }, {
            "index": 23,
            "keyword": "搜索关键词-22",
            "count": 946,
            "range": 74,
            "status": 1
        }, {
            "index": 24,
            "keyword": "搜索关键词-23",
            "count": 201,
            "range": 22,
            "status": 1
        }, {
            "index": 25,
            "keyword": "搜索关键词-24",
            "count": 679,
            "range": 72,
            "status": 0
        }, {
            "index": 26,
            "keyword": "搜索关键词-25",
            "count": 486,
            "range": 44,
            "status": 1
        }, {
            "index": 27,
            "keyword": "搜索关键词-26",
            "count": 884,
            "range": 2,
            "status": 0
        }, {
            "index": 28,
            "keyword": "搜索关键词-27",
            "count": 415,
            "range": 88,
            "status": 1
        }, {
            "index": 29,
            "keyword": "搜索关键词-28",
            "count": 77,
            "range": 95,
            "status": 1
        }, {
            "index": 30,
            "keyword": "搜索关键词-29",
            "count": 277,
            "range": 12,
            "status": 1
        }, {
            "index": 31,
            "keyword": "搜索关键词-30",
            "count": 891,
            "range": 90,
            "status": 0
        }, {
            "index": 32,
            "keyword": "搜索关键词-31",
            "count": 474,
            "range": 80,
            "status": 0
        }, {
            "index": 33,
            "keyword": "搜索关键词-32",
            "count": 447,
            "range": 87,
            "status": 0
        }, {
            "index": 34,
            "keyword": "搜索关键词-33",
            "count": 312,
            "range": 29,
            "status": 0
        }, {
            "index": 35,
            "keyword": "搜索关键词-34",
            "count": 359,
            "range": 75,
            "status": 0
        }, {
            "index": 36,
            "keyword": "搜索关键词-35",
            "count": 221,
            "range": 21,
            "status": 1
        }, {
            "index": 37,
            "keyword": "搜索关键词-36",
            "count": 465,
            "range": 28,
            "status": 0
        }, {
            "index": 38,
            "keyword": "搜索关键词-37",
            "count": 887,
            "range": 83,
            "status": 0
        }, {
            "index": 39,
            "keyword": "搜索关键词-38",
            "count": 906,
            "range": 4,
            "status": 1
        }, {
            "index": 40,
            "keyword": "搜索关键词-39",
            "count": 906,
            "range": 7,
            "status": 0
        }, {
            "index": 41,
            "keyword": "搜索关键词-40",
            "count": 702,
            "range": 39,
            "status": 1
        }, {
            "index": 42,
            "keyword": "搜索关键词-41",
            "count": 223,
            "range": 62,
            "status": 1
        }, {
            "index": 43,
            "keyword": "搜索关键词-42",
            "count": 15,
            "range": 30,
            "status": 1
        }, {
            "index": 44,
            "keyword": "搜索关键词-43",
            "count": 615,
            "range": 3,
            "status": 1
        }, {
            "index": 45,
            "keyword": "搜索关键词-44",
            "count": 563,
            "range": 78,
            "status": 1
        }, {
            "index": 46,
            "keyword": "搜索关键词-45",
            "count": 779,
            "range": 8,
            "status": 0
        }, {
            "index": 47,
            "keyword": "搜索关键词-46",
            "count": 441,
            "range": 94,
            "status": 1
        }, {
            "index": 48,
            "keyword": "搜索关键词-47",
            "count": 628,
            "range": 23,
            "status": 0
        }, {
            "index": 49,
            "keyword": "搜索关键词-48",
            "count": 817,
            "range": 87,
            "status": 1
        }, {
            "index": 50,
            "keyword": "搜索关键词-49",
            "count": 658,
            "range": 73,
            "status": 0
        }],
        "offlineData": [{
            "name": "Stores 0",
            "cvr": 0.1
        }, {
            "name": "Stores 1",
            "cvr": 0.9
        }, {
            "name": "Stores 2",
            "cvr": 0.5
        }, {
            "name": "Stores 3",
            "cvr": 0.7
        }, {
            "name": "Stores 4",
            "cvr": 0.7
        }, {
            "name": "Stores 5",
            "cvr": 0.5
        }, {
            "name": "Stores 6",
            "cvr": 0.3
        }, {
            "name": "Stores 7",
            "cvr": 0.7
        }, {
            "name": "Stores 8",
            "cvr": 0.6
        }, {
            "name": "Stores 9",
            "cvr": 0.7
        }],
        "offlineChartData": [{
            "x": 1546719222652,
            "y1": 105,
            "y2": 52
        }, {
            "x": 1546721022652,
            "y1": 101,
            "y2": 14
        }, {
            "x": 1546722822652,
            "y1": 19,
            "y2": 25
        }, {
            "x": 1546724622652,
            "y1": 98,
            "y2": 80
        }, {
            "x": 1546726422652,
            "y1": 81,
            "y2": 78
        }, {
            "x": 1546728222652,
            "y1": 22,
            "y2": 14
        }, {
            "x": 1546730022652,
            "y1": 76,
            "y2": 65
        }, {
            "x": 1546731822652,
            "y1": 11,
            "y2": 79
        }, {
            "x": 1546733622652,
            "y1": 108,
            "y2": 102
        }, {
            "x": 1546735422652,
            "y1": 19,
            "y2": 101
        }, {
            "x": 1546737222652,
            "y1": 45,
            "y2": 105
        }, {
            "x": 1546739022652,
            "y1": 73,
            "y2": 60
        }, {
            "x": 1546740822652,
            "y1": 36,
            "y2": 13
        }, {
            "x": 1546742622652,
            "y1": 14,
            "y2": 34
        }, {
            "x": 1546744422652,
            "y1": 26,
            "y2": 19
        }, {
            "x": 1546746222652,
            "y1": 13,
            "y2": 101
        }, {
            "x": 1546748022652,
            "y1": 53,
            "y2": 30
        }, {
            "x": 1546749822652,
            "y1": 35,
            "y2": 16
        }, {
            "x": 1546751622652,
            "y1": 39,
            "y2": 76
        }, {
            "x": 1546753422652,
            "y1": 93,
            "y2": 89
        }],
        "salesTypeData": [{
            "x": "家用电器",
            "y": 4544
        }, {
            "x": "食用酒水",
            "y": 3321
        }, {
            "x": "个护健康",
            "y": 3113
        }, {
            "x": "服饰箱包",
            "y": 2341
        }, {
            "x": "母婴产品",
            "y": 1231
        }, {
            "x": "其他",
            "y": 1231
        }],
        "salesTypeDataOnline": [{
            "x": "家用电器",
            "y": 244
        }, {
            "x": "食用酒水",
            "y": 321
        }, {
            "x": "个护健康",
            "y": 311
        }, {
            "x": "服饰箱包",
            "y": 41
        }, {
            "x": "母婴产品",
            "y": 121
        }, {
            "x": "其他",
            "y": 111
        }],
        "salesTypeDataOffline": [{
            "x": "家用电器",
            "y": 99
        }, {
            "x": "食用酒水",
            "y": 188
        }, {
            "x": "个护健康",
            "y": 344
        }, {
            "x": "服饰箱包",
            "y": 255
        }, {
            "x": "其他",
            "y": 65
        }],
        "radarData": [{
            "name": "个人",
            "label": "引用",
            "value": 10
        }, {
            "name": "个人",
            "label": "口碑",
            "value": 8
        }, {
            "name": "个人",
            "label": "产量",
            "value": 4
        }, {
            "name": "个人",
            "label": "贡献",
            "value": 5
        }, {
            "name": "个人",
            "label": "热度",
            "value": 7
        }, {
            "name": "团队",
            "label": "引用",
            "value": 3
        }, {
            "name": "团队",
            "label": "口碑",
            "value": 9
        }, {
            "name": "团队",
            "label": "产量",
            "value": 6
        }, {
            "name": "团队",
            "label": "贡献",
            "value": 3
        }, {
            "name": "团队",
            "label": "热度",
            "value": 1
        }, {
            "name": "部门",
            "label": "引用",
            "value": 4
        }, {
            "name": "部门",
            "label": "口碑",
            "value": 1
        }, {
            "name": "部门",
            "label": "产量",
            "value": 6
        }, {
            "name": "部门",
            "label": "贡献",
            "value": 5
        }, {
            "name": "部门",
            "label": "热度",
            "value": 7
        }]
    }
}