export default {
    data: {
        list:[{
            "id": "fake-list-0", "owner": "付小小", "title": "Alipay", "avatar": "https://gw.alipayobjects.com/zos/rmsportal/WdGqmHpayyMjiEhcKoVE.png", "cover": "https://gw.alipayobjects.com/zos/rmsportal/uMfMFlvUuceEyPpotzlq.png", "status": "active", "percent": 74, "logo": "https://gw.alipayobjects.com/zos/rmsportal/WdGqmHpayyMjiEhcKoVE.png", "href": "https://ant.design", "updatedAt": "2019-01-05T01:01:05.262Z", "createdAt": "2019-01-05T01:01:05.262Z", "subDescription": "那是一种内在的东西， 他们到达不了，也无法触及的", "description": "在中台产品的研发过程中，会出现不同的设计规范和实现方式，但其中往往存在很多类似的页面和组件，这些类似的组件会被抽离成一套标准规范。", "activeUser": 153109, "newUser": 1473, "star": 102, "like": 126, "message": 12, "content": "段落示意：蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。", "members": [{ "avatar": "https://gw.alipayobjects.com/zos/rmsportal/ZiESqWwCXBRQoaPONSJe.png", "name": "曲丽丽", "id": "member1" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/tBOxZPlITHqwlGjsJWaF.png", "name": "王昭君", "id": "member2" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/sBxjgqiuHMGRkIjqlQCd.png", "name": "董娜娜", "id": "member3" }]
        }, {
            "id": "fake-list-1", "owner": "曲丽丽", "title": "Angular", "avatar": "https://gw.alipayobjects.com/zos/rmsportal/zOsKZmFRdUtvpqCImOVY.png", "cover": "https://gw.alipayobjects.com/zos/rmsportal/iZBVOIhGJiAnhplqjvZW.png", "status": "exception", "percent": 58, "logo": "https://gw.alipayobjects.com/zos/rmsportal/zOsKZmFRdUtvpqCImOVY.png", "href": "https://ant.design", "updatedAt": "2019-01-04T23:01:05.262Z", "createdAt": "2019-01-04T23:01:05.262Z", "subDescription": "希望是一个好东西，也许是最好的，好东西是不会消亡的", "description": "在中台产品的研发过程中，会出现不同的设计规范和实现方式，但其中往往存在很多类似的页面和组件，这些类似的组件会被抽离成一套标准规范。", "activeUser": 173432, "newUser": 1626, "star": 114, "like": 152, "message": 17, "content": "段落示意：蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。", "members": [{ "avatar": "https://gw.alipayobjects.com/zos/rmsportal/ZiESqWwCXBRQoaPONSJe.png", "name": "曲丽丽", "id": "member1" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/tBOxZPlITHqwlGjsJWaF.png", "name": "王昭君", "id": "member2" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/sBxjgqiuHMGRkIjqlQCd.png", "name": "董娜娜", "id": "member3" }]
        }, {
            "id": "fake-list-2", "owner": "林东东", "title": "Ant Design", "avatar": "https://gw.alipayobjects.com/zos/rmsportal/dURIMkkrRFpPgTuzkwnB.png", "cover": "https://gw.alipayobjects.com/zos/rmsportal/iXjVmWVHbCJAyqvDxdtx.png", "status": "normal", "percent": 100, "logo": "https://gw.alipayobjects.com/zos/rmsportal/dURIMkkrRFpPgTuzkwnB.png", "href": "https://ant.design", "updatedAt": "2019-01-04T21:01:05.262Z", "createdAt": "2019-01-04T21:01:05.262Z", "subDescription": "生命就像一盒巧克力，结果往往出人意料", "description": "在中台产品的研发过程中，会出现不同的设计规范和实现方式，但其中往往存在很多类似的页面和组件，这些类似的组件会被抽离成一套标准规范。", "activeUser": 146669, "newUser": 1112, "star": 150, "like": 135, "message": 20, "content": "段落示意：蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。", "members": [{ "avatar": "https://gw.alipayobjects.com/zos/rmsportal/ZiESqWwCXBRQoaPONSJe.png", "name": "曲丽丽", "id": "member1" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/tBOxZPlITHqwlGjsJWaF.png", "name": "王昭君", "id": "member2" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/sBxjgqiuHMGRkIjqlQCd.png", "name": "董娜娜", "id": "member3" }]
        }, {
            "id": "fake-list-3", "owner": "周星星", "title": "Ant Design Pro", "avatar": "https://gw.alipayobjects.com/zos/rmsportal/sfjbOqnsXXJgNCjCzDBL.png", "cover": "https://gw.alipayobjects.com/zos/rmsportal/gLaIAoVWTtLbBWZNYEMg.png", "status": "active", "percent": 51, "logo": "https://gw.alipayobjects.com/zos/rmsportal/sfjbOqnsXXJgNCjCzDBL.png", "href": "https://ant.design", "updatedAt": "2019-01-04T19:01:05.262Z", "createdAt": "2019-01-04T19:01:05.262Z", "subDescription": "城镇中有那么多的酒馆，她却偏偏走进了我的酒馆", "description": "在中台产品的研发过程中，会出现不同的设计规范和实现方式，但其中往往存在很多类似的页面和组件，这些类似的组件会被抽离成一套标准规范。", "activeUser": 132504, "newUser": 1044, "star": 137, "like": 181, "message": 14, "content": "段落示意：蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。", "members": [{ "avatar": "https://gw.alipayobjects.com/zos/rmsportal/ZiESqWwCXBRQoaPONSJe.png", "name": "曲丽丽", "id": "member1" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/tBOxZPlITHqwlGjsJWaF.png", "name": "王昭君", "id": "member2" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/sBxjgqiuHMGRkIjqlQCd.png", "name": "董娜娜", "id": "member3" }]
        }, {
            "id": "fake-list-4", "owner": "吴加好", "title": "Bootstrap", "avatar": "https://gw.alipayobjects.com/zos/rmsportal/siCrBXXhmvTQGWPNLBow.png", "cover": "https://gw.alipayobjects.com/zos/rmsportal/gLaIAoVWTtLbBWZNYEMg.png", "status": "exception", "percent": 70, "logo": "https://gw.alipayobjects.com/zos/rmsportal/siCrBXXhmvTQGWPNLBow.png", "href": "https://ant.design", "updatedAt": "2019-01-04T17:01:05.262Z", "createdAt": "2019-01-04T17:01:05.262Z", "subDescription": "那时候我只会想自己想要什么，从不想自己拥有什么", "description": "在中台产品的研发过程中，会出现不同的设计规范和实现方式，但其中往往存在很多类似的页面和组件，这些类似的组件会被抽离成一套标准规范。", "activeUser": 123370, "newUser": 1173, "star": 114, "like": 173, "message": 18, "content": "段落示意：蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。蚂蚁金服设计平台 ant.design，用最小的工作量，无缝接入蚂蚁金服生态，提供跨越设计与开发的体验解决方案。", "members": [{ "avatar": "https://gw.alipayobjects.com/zos/rmsportal/ZiESqWwCXBRQoaPONSJe.png", "name": "曲丽丽", "id": "member1" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/tBOxZPlITHqwlGjsJWaF.png", "name": "王昭君", "id": "member2" }, { "avatar": "https://gw.alipayobjects.com/zos/rmsportal/sBxjgqiuHMGRkIjqlQCd.png", "name": "董娜娜", "id": "member3" }]
        }]
    }
}